### ISSUE TITLE
PDF Illisible

### ISSUE THREAD

**Issue by Tolb** [Nainterceptor/ENIDownloader#1]
Bonjour,

Je ne parviens pas à obtenir des pdf lisibles, même avec le "if".
J'ai bien le bon nombre de PDF, lorsque je les ouvre avec gedit j'ai : 
`<script type='text/javascript'> window.opener.location='logout.aspx?cfgsite=Default&cfgbdd=NomdeMaBase&idlng=1&ac=1';self.close();</script>`

NomdeMaBase n'est pas le vrai nom :)

Merci pour le travail accompli.
Et j'espère à bientôt.

**Comment by Nainterceptor** [comment]
Ils ont peut être rajoutés un moyen technique de détection, je réessaye quand j'en aurai l'occasion.

**Comment by MisterGREEN78** [comment]
Hello Nainterceptor,

Je viens de tester ton application mais je rencontre le même souci que Tolb, les fichiers pdf générés contiennent juste les 2 lignes <script type..........

Les messages précédents étant de Mai je ne sais pas si tu as pû jeter un coup d'oeil depuis.

En tout cas chapeau et merci à toi

Cordialement,
Green

**Comment by Tolb** [comment]
Bonjour,

Çà fonctionne pour moi.
Le problème était que la fonction d'export (bouton export pdf) était désactivé sur mon compte.

Merci en tout cas et beau boulot!

**Comment by cochise57** [comment]
Bonjour,
Comment avez-vous fait pour résoudre le problème?
Cordialement

**Comment by cochise57** [comment]
Bonjour, 
J'ai chercher toute la matinée comment je pourrais faire mais lorsque je tente de lancer la fonction getPDF je me fais déco immédiatement, et lorsque je vais sur le liens pour générer un pdf, j'ai page blanche. Avez-vous une solution?
Cordialement,

**Comment by fresnault** [comment]
Bonjour,

Je n'arrive pas non plus à accéder aux resources, j'ai le message d'erreur suivant dans les PDF : 
`<script type='text/javascript'>    window.opener.location='logout.aspx?cfgsite=BN&cfgbdd=SITEWEB&idlng=1&ac=1&idc=1';self.close();</script>`

Le bouton export PDF est désactivé sur mon compte, c'est le cas de tout le monde, non ?

Cordialement

**Comment by cochise57** [comment]
Bonjour fresnault,
J'avais également le bouton export PDF désactiver, je pense que c'est dû à cela l'erreur. Si tu trouves une solution je suis prenant, car je n'en est trouvé aucune.
Cordialement,

**Comment by Nainterceptor** [comment]
Ahaha, la seule solution qu'ils ont trouvé plus nous faire + chier c'est désactiver ça aussi :)
Essayez de générer vous même un pdf depuis le html...

**Comment by Tolb** [comment]
Bonjour,

Désolé pour la réponse tardive.

Il faut demander à ENI de vous activer la fonctionnalité.
Dans mon cas, c'était du au fait qu'il y avait des comptes non nominatif.
C'est automatique, sinon votre nom n’apparait pas en filigrane sur les exports.

**Comment by Nainterceptor** [comment]
Merci @Tolb pour la réponse, je ferme le ticket du coup !
